### ISSUE TITLE
Broken workflow for setting server url remotely

### ISSUE THREAD

**Issue by mikldt** [concerto/bandshell#48]
We want to be able to set the root domain for a newly-installed screen from a remote PC (portable device) when that infor is not pre-built into the image and keyboard and mouse are not available. I ran into two problems when testing this workflow:

* When the URL is updated through the bandshell web interface remotely, it first resulted in a 500. Re-submitting the page and reloading the page caused it to work.
* After submitting the new URL, the player is still at /setup. The only way to get it to get it to the actual screen display domain is to hard-reboot the PC or connect a keyboard.

**Comment by augustf** [comment]
@mikldt Any idea why the first bit of this issue only occurs remotely? When we deployed screens with a keyboard in-hand, this wasn't an issue at all.
